### ISSUE TITLE
CreateCondaEnvironmentException

### ISSUE THREAD

**Issue by tpall** [avilab/snakemake-wrappers#1]
```
Building DAG of jobs...
Creating conda environment https:/github.com/avilab/snakemake-wrappers/tree/master/parse-blast
/environment.yaml...
Downloading remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /tmp/tmpt32xgkms.yaml:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/conda/exceptions.py"
, line 819, in __call__
        return func(*args, **kwargs)
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/conda_env/cli/main.p
y", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/conda_env/cli/main_c
reate.py", line 79, in execute
        directory=os.getcwd())
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/conda_env/specs/__in
it__.py", line 20, in detect
        if spec.can_handle():
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/conda_env/specs/yaml
_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/conda_env/env.py", l
ine 84, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/conda_env/env.py", l
ine 72, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/conda/common/seriali
ze.py", line 74, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/ruamel_yaml/main.py", line 640, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/ruamel_yaml/constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 75, in get_single_node
        document = self.compose_document()
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 99, in compose_document
        self.parser.get_event()
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 166, in get_event
        self.current_event = self.state()
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 244, in parse_document_end
        token = self.scanner.peek_token()
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 173, in peek_token
        self.fetch_more_tokens()
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 273, in fetch_more_tokens
        return self.fetch_value()
      File "/gpfs/hpc/home/taavi74/miniconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 626, in fetch_value
        self.reader.get_mark())
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 528, column 26:
            <!-- blob contrib key: blob_contributors:v21:0a4fbd8f ... 
                                 ^ (line: 528)

`$ /gpfs/hpc/home/taavi74/miniconda3/bin/conda-env create --file /gpfs/hpc/home/taavi74/fastq/prjna361402/.snakemake/conda/48640b1f.yaml --prefix /gpfs/hpc/home/taavi74/fastq/prjna361402/.snakemake/conda/48640b1f`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=viruscount
                CONDA_EXE=/gpfs/hpc/home/taavi74/miniconda3/bin/conda
             CONDA_PREFIX=/gpfs/hpc/home/taavi74/miniconda3/envs/viruscount
    CONDA_PROMPT_MODIFIER=(viruscount)
         CONDA_PYTHON_EXE=/gpfs/hpc/home/taavi74/miniconda3/bin/python
               CONDA_ROOT=/gpfs/hpc/home/taavi74/miniconda3
              CONDA_SHLVL=1
  LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64:MODULEPATH=/usr/share/Modules/modulefiles:/storage/software/modulefilesPATH=/gpfs/hpc/home/taavi74/miniconda3/envs/viruscount/bin:/gpfs/hpc/home/taavi74/miniconda3/bin:/usr/local/cuda/bin:/gpfs/hpc/home/taavi74/miniconda3/bin:/usr/local/cuda/bin:/usr/bin/:/gpfs/hpchome/taavi74/miniconda3/bin:/gpfs/hpchome/taavi74/miniconda3/bin:/usr/local/cuda/bin:/gpfs/hpchome/taavi74/miniconda3/bin:/gpfs/hpchome/taavi74/miniconda3/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/gpfs/hpchome/taavi74/bin:/gpfs/hpchome/taavi74/.local/
                          bin:/gpfs/hpchome/taavi74/bin:/gpfs/hpchome/taavi74/bin:/gpfs/hpchome/
                          taavi74/bin:/gpfs/hpchome/taavi74/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : viruscount
    active env location : /gpfs/hpc/home/taavi74/miniconda3/envs/viruscount
            shell level : 1
       user config file : /gpfs/hpchome/taavi74/.condarc
 populated config files : /gpfs/hpchome/taavi74/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /gpfs/hpc/home/taavi74/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /gpfs/hpc/home/taavi74/miniconda3/pkgs
                          /gpfs/hpchome/taavi74/.conda/pkgs
       envs directories : /gpfs/hpc/home/taavi74/miniconda3/envs
                          /gpfs/hpchome/taavi74/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/3.10.0-693.2.2.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 229985:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:
No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

**Comment by tpall** [comment]
Github repo cannot be used as a snakemake wrapper by providing url to wrapper subfolder of github ui. Exception was caused by html. 

Direct url to a __raw.githubusercontent__ folder like so: 

```
wrapper:
    "https://raw.githubusercontent.com/avilab/snakemake-wrappers/master/parse-blast"
```

Snakemake wrapper looks for `environment.yaml`, `wrapper.py` (, `meta.yaml`) files.
