### ISSUE TITLE
handling http error message

### ISSUE THREAD

**Issue by tpall** [avilab/snakemake-wrappers#2]
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       upload
        1

[Mon Feb 18 09:24:58 2019]
rule upload:
    input: results/SRR5580156_phages_viruses_1.csv, results/SRR5580156_phages_viruses_2.csv, results/SRR5580156_phages_viruses_3.csv, results/$
    output: results/SRR5580156_phages_viruses.csv.tar.gz
    jobid: 0
    wildcards: sample=SRR5580156, result=phages_viruses, ext=csv

Activating conda environment: /gpfs/hpchome/radko/Projects/prjna361402/.snakemake/conda/4f3133f2
Traceback (most recent call last):
  File "/gpfs/hpchome/radko/Projects/prjna361402/.snakemake/scripts/tmp_ko7y956.wrapper.py", line 50, in <module>
    raise requests.HTTPError(f"Error in data upload, status code: {r.status_code}   {r.json()['message']}")
  File "/gpfs/hpchome/radko/Projects/prjna361402/.snakemake/conda/4f3133f2/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/gpfs/hpchome/radko/Projects/prjna361402/.snakemake/conda/4f3133f2/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/gpfs/hpchome/radko/Projects/prjna361402/.snakemake/conda/4f3133f2/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/gpfs/hpchome/radko/Projects/prjna361402/.snakemake/conda/4f3133f2/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[Mon Feb 18 09:26:54 2019]
Error in rule upload:

RuleException:
CalledProcessError in line 267 of /gpfs/hpchome/radko/Projects/vs/rules/blast.smk:
Command 'source activate /gpfs/hpchome/radko/Projects/prjna361402/.snakemake/conda/4f3133f2; set -euo pipefail;  python /gpfs/hpchome/radko/Pr$
  File "/gpfs/hpchome/radko/Projects/vs/rules/blast.smk", line 267, in __rule_upload
  File "/gpfs/hpchome/radko/miniconda3/envs/snakemake/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job upload since they might be corrupted:
results/SRR5580156_phages_viruses.csv.tar.gz
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by tpall** [comment]
Status code was 504. 

Request failed, due to an internal server error. **Error response NOT included.** Don’t worry, Zenodo admins have been notified and will be dealing with the problem ASAP.

**Comment by tpall** [comment]
Solved by @da2f6f7dcd130a4b66534f86dadb93ab701afb56
